name: Android Appium Tests

on:
  schedule:
    - cron: '20 15 * * *'  # 10:05 UTC = 17:05 GMT+7 (Chạy vào 5 phút sau 10:00 AM UTC mỗi ngày)
  workflow_dispatch:      # Cho phép chạy thủ công nếu cần

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        device: [ 'Samsung Galaxy S22 Ultra', 'Samsung Galaxy S21', 'Google Pixel 6 Pro' ]
        os: [ 'android' ]
        osVersion: [ '12.0', '11.0' ]
    name: Test Android - ${{ matrix.device }} - ${{ matrix.osVersion }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Thiết lập Java, vì Appium yêu cầu Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Cài đặt Appium và các dependencies cần thiết
      - name: Install Appium
        run: |
          npm install -g appium

      - name: Install Appium Android Driver
        run: |
          npm install appium-app-android-driver

      # Chạy kiểm thử Appium với BrowserStack
      - name: Run Appium tests on BrowserStack
        run: |
          # Lưu trữ thông tin bảo mật
          export BROWSERSTACK_USERNAME=thanhvo_DtH7RP
          export BROWSERSTACK_ACCESS_KEY=AH576ScJ6B8qgD1DxLz6

          # Tạo file cấu hình cho BrowserStack
          cat > browserstack_config.json <<EOF
          {
            "userName": "$BROWSERSTACK_USERNAME",
            "accessKey": "$BROWSERSTACK_ACCESS_KEY",
            "projectName": "Android Appium Tests",
            "buildName": "browserstack-build-${{ github.run_id }}",
            "platforms": [
              {
                "deviceName": "${{ matrix.device }}",
                "osVersion": "${{ matrix.osVersion }}",
                "platformName": "android",
                "app": "bs://<your_app_hash_here>"  # Thay <your_app_hash_here> bằng hash ứng dụng thực tế
              }
            ],
            "parallelsPerPlatform": 1,
            "browserstackLocal": true,
            "debug": false,
            "networkLogs": false,
            "consoleLogs": "errors"
          }
          EOF

          # Chạy kiểm thử trên BrowserStack
          appium --use-legacy-packages --plugin browserstack --config browserstack_config.json

      # Tải kết quả kiểm thử lên GitHub Actions (nếu có)
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-output/
