name: Android Appium Tests on BrowserStack

on:
  schedule:
    - cron: '50 14 * * *'  # Chạy vào 14:50 UTC (17:50 GMT+7)
  workflow_dispatch:      # Cho phép chạy thủ công

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout mã nguồn

      # Thiết lập JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Cài đặt Node.js phiên bản 18 (hoặc cao hơn)
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Cài đặt Appium
      - name: Install Appium and dependencies
        run: |
          npm install -g npm@latest  # Cập nhật npm lên phiên bản mới nhất
          npm install -g appium      # Cài đặt Appium

      # Cài đặt Appium Android Driver từ GitHub nếu npm registry không tìm thấy
      - name: Install Appium Android Driver
        run: |
          npm install appium/appium-app-android-driver#master

      # Thiết lập BrowserStack Credentials
      - name: Set BrowserStack Credentials
        run: |
          echo "BROWSERSTACK_USERNAME=${{ secrets.BROWSERSTACK_USERNAME }}" >> $GITHUB_ENV
          echo "BROWSERSTACK_ACCESS_KEY=${{ secrets.BROWSERSTACK_ACCESS_KEY }}" >> $GITHUB_ENV

      # Tạo file cấu hình BrowserStack từ các biến môi trường và JSON cấu hình
      - name: Create BrowserStack Config
        run: |
          echo "Creating browserstack_config.json"
          cat > browserstack_config.json <<EOF
          {
            "userName": "$BROWSERSTACK_USERNAME",
            "accessKey": "$BROWSERSTACK_ACCESS_KEY",
            "projectName": "BrowserStack Samples",
            "buildName": "browserstack build",
            "buildIdentifier": "#${{ github.run_id }}",
            "framework": "testng",
            "source": "testng:appium-sample-sdk:v1.1",
            "app": "./WikipediaSample.apk",
            "platforms": [
              {
                "deviceName": "Samsung Galaxy S22 Ultra",
                "osVersion": "12.0",
                "platformName": "android"
              },
              {
                "deviceName": "Samsung Galaxy S21",
                "osVersion": "11.0",
                "platformName": "android"
              },
              {
                "deviceName": "Google Pixel 6 Pro",
                "osVersion": "12.0",
                "platformName": "android"
              }
            ],
            "parallelsPerPlatform": 1,
            "browserstackLocal": true,
            "debug": false,
            "networkLogs": false,
            "consoleLogs": "errors"
          }
          EOF
          cat browserstack_config.json  # In ra file cấu hình để kiểm tra

      # Chạy kiểm thử trên BrowserStack
      - name: Run Appium Tests on BrowserStack
        run: |
          appium --config browserstack_config.json

      # Upload kết quả kiểm thử
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-output/
