name: Android CI

on:
  schedule:
    - cron: '07 14 * * *'  # Chạy vào 1:55 PM mỗi ngày (UTC)
  workflow_dispatch:  # Cho phép chạy thủ công nếu cần
    inputs:
      commit_sha:
        description: 'The full commit id to build'
        required: true

jobs:
  android-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]  # Chỉ sử dụng Java 21
        os: [ 'macos-latest', 'windows-latest', 'ubuntu-latest' ]
    name: Test Android - ${{ matrix.java }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      # Cài đặt Java 21
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      # Chạy kiểm tra Android với TestNG
      - name: Run mvn test for TestNG Android
        run: |
          cd android/testng-examples
          mvn compile
          mvn test
