name: Android Appium Tests on BrowserStack

on:
  schedule:
    - cron: '35 15 * * *'  # Chạy vào 10:05 UTC (17:05 GMT+7)
  workflow_dispatch:      # Cho phép chạy thủ công

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Thiết lập JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Cài đặt Node.js phiên bản 18 (hoặc cao hơn)
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Cài đặt Appium và các dependencies
      - name: Install Appium and dependencies
        run: |
          npm install -g npm@latest  # Cập nhật npm lên phiên bản mới nhất
          npm install -g appium      # Cài đặt Appium

      # Cài đặt Appium Android Driver (Sử dụng gói chính thức)
      - name: Install Appium Android Driver
        run: |
          npm install appium-android-driver

      # Thiết lập BrowserStack Credentials
      - name: Set BrowserStack Credentials
        run: |
          echo "BROWSERSTACK_USERNAME=${{ secrets.BROWSERSTACK_USERNAME }}" >> $GITHUB_ENV
          echo "BROWSERSTACK_ACCESS_KEY=${{ secrets.BROWSERSTACK_ACCESS_KEY }}" >> $GITHUB_ENV

      # Tạo file cấu hình BrowserStack
      - name: Create BrowserStack Config
        run: |
          cat > browserstack_config.json <<EOF
          {
            "userName": "$BROWSERSTACK_USERNAME",
            "accessKey": "$BROWSERSTACK_ACCESS_KEY",
            "projectName": "Android Appium Tests on BrowserStack",
            "buildName": "browserstack-build-${{ github.run_id }}",
            "platforms": [
              {
                "deviceName": "Samsung Galaxy S22 Ultra",
                "osVersion": "12.0",
                "platformName": "android",
                "app": "bs://<your_app_hash_here>"
              },
              {
                "deviceName": "Samsung Galaxy S21",
                "osVersion": "11.0",
                "platformName": "android",
                "app": "bs://<your_app_hash_here>"
              }
            ],
            "parallelsPerPlatform": 1,
            "browserstackLocal": true,
            "debug": true,
            "networkLogs": true,
            "consoleLogs": "errors"
          }
          EOF

      # Chạy kiểm thử trên BrowserStack
      - name: Run Appium Tests on BrowserStack
        run: |
          appium --use-legacy-packages --plugin browserstack --config browserstack_config.json

      # Upload kết quả kiểm thử
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-output/
