name: Android BrowserStack CI

on:
  schedule:
    - cron: '20 14 * * *'  # Lịch trình chạy vào 14:20 PM UTC mỗi ngày
  workflow_dispatch:  # Cho phép chạy thủ công nếu cần

jobs:
  browserstack-android-test:
    runs-on: ubuntu-latest  # Sử dụng máy chủ CI trên ubuntu-latest

    strategy:
      matrix:
        device: [ 'Samsung Galaxy S22 Ultra', 'Samsung Galaxy S21', 'Google Pixel 6 Pro' ]
        osVersion: [ '12.0', '11.0' ]
        platformName: [ 'android' ]  # Đảm bảo tên hệ điều hành được xác định đúng

    name: Test Android - ${{ matrix.device }} - ${{ matrix.osVersion }}

    steps:
      # Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Thiết lập môi trường Java (Appium yêu cầu Java)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Cài đặt Appium
      - name: Install Appium
        run: |
          npm install -g appium

      # Cài đặt các dependencies cần thiết cho Appium và Appium Android Driver
      - name: Install Android dependencies
        run: |
          npm install appium-app-android-driver
          npm install appium

      # Chạy kiểm thử Appium với BrowserStack
      - name: Run Appium tests on BrowserStack
        run: |
          # Sử dụng GitHub Secrets cho BrowserStack Credentials
          export BROWSERSTACK_USERNAME=${{ secrets.BROWSERSTACK_USERNAME }}
          export BROWSERSTACK_ACCESS_KEY=${{ secrets.BROWSERSTACK_ACCESS_KEY }}

          # Tạo file cấu hình cho BrowserStack
          cat > browserstack_config.json <<EOF
          {
            "userName": "$BROWSERSTACK_USERNAME",
            "accessKey": "$BROWSERSTACK_ACCESS_KEY",
            "projectName": "Android BrowserStack CI",
            "buildName": "browserstack-build-${{ github.run_id }}",
            "platforms": [
              {
                "deviceName": "${{ matrix.device }}",
                "osVersion": "${{ matrix.osVersion }}",
                "platformName": "android",
                "app": "bs://<your_app_hash_here>"  # Đây là ứng dụng bạn đã tải lên BrowserStack, thay <your_app_hash_here> bằng hash của ứng dụng thực tế
              }
            ],
            "parallelsPerPlatform": 1,
            "browserstackLocal": true,
            "debug": false,
            "networkLogs": false,
            "consoleLogs": "errors"
          }
          EOF

          # Chạy kiểm thử trên BrowserStack
          appium --use-legacy-packages --plugin browserstack --config browserstack_config.json

      # Lưu trữ các kết quả kiểm tra dưới dạng artifacts (Ví dụ: logs, videos)
      - name: Upload BrowserStack logs and videos as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: browserstack-logs
          path: ./path-to-logs-or-videos-directory  # Đảm bảo rằng bạn đã chỉ định đúng đường dẫn đến thư mục chứa logs hoặc videos mà BrowserStack đã tạo ra
