name: Java CI with JDK 21

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '24 12 * * *'  # Mỗi ngày vào 12:10 PM UTC (tương ứng với 7:10 PM UTC+7)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Verify JDK Version
        run: java -version  # In ra phiên bản Java đang được sử dụng

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
