name: Android Appium Tests

on:
  schedule:
    - cron: '45 12 * * *'  # 12:35 PM UTC = 7:35 PM GMT+7
  workflow_dispatch:      # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-output/
