name: Java SDK Test workflow for Maven on workflow_dispatch

on:
  # Thêm cron để tự động chạy vào lúc 10h10 AM hàng ngày
  schedule:
    - cron: '21 10 * * *'  # Thời gian chạy là 10h10 AM mỗi ngày
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'The full commit id to build'
        required: true

jobs:
  comment-run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        java: [ '8', '11', '17' ]
        os: [ 'macos-latest', 'windows-latest', 'ubuntu-latest' ]
    name: TestNG Appium Repo ${{ matrix.java }} - ${{ matrix.os }} Sample
    env:
      # Lưu ý: Đảm bảo rằng bạn đã lưu BROWSERSTACK_USERNAME và BROWSERSTACK_ACCESS_KEY vào GitHub Secrets
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      # 1. Checkout the code from the specified commit
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      # 2. Cập nhật trạng thái của commit
      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        id: status-check-in-progress
        env:
          job_name: TestNG Appium Repo ${{ matrix.java }} - ${{ matrix.os }} Sample
          commit_sha: ${{ github.event.inputs.commit_sha }}
        with:
          github-token: ${{ github.token }}
          script: |
            const result = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: process.env.job_name,
              head_sha: process.env.commit_sha,
              status: 'in_progress'
            }).catch((err) => ({status: err.status, response: err.response}));
            console.log(`The status-check response : ${result.status} Response : ${JSON.stringify(result.response)}`)
            if (result.status !== 201) {
              console.log('Failed to create check run')
            }

      # 3. Thiết lập môi trường Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      # 4. Thiết lập BrowserStack Local nếu cần
      - name: Set up BrowserStack Local
        run: |
          curl -o BrowserStackLocal.zip https://www.browserstack.com/browserstack-local/BrowserStackLocal.zip
          unzip BrowserStackLocal.zip
          ./BrowserStackLocal --key ${{ secrets.BROWSERSTACK_ACCESS_KEY }} &

      # 5. Chạy các bài kiểm tra Android với BrowserStack
      - name: Run mvn test for testng android
        run: |
          cd android/testng-examples
          mvn compile
          mvn test

      # 6. Chạy mvn profile sample-test cho Android
      - name: Run mvn profile sample-test for testng android
        run: |
          cd android/testng-examples
          mvn compile
          mvn test -P sample-test

      # 7. Chạy mvn profile sample-local-test cho Android (sử dụng BrowserStack Local)
      - name: Run mvn profile sample-local-test for testng android
        run: |
          cd android/testng-examples
          mvn compile
          mvn test -P sample-local-test -D"browserstack.app"="./LocalSample.apk"

      # 8. Chạy các bài kiểm tra iOS với BrowserStack
      - name: Run mvn test for testng ios
        run: |
          cd ios/testng-examples
          mvn compile
          mvn test

      # 9. Chạy mvn profile sample-test cho iOS
      - name: Run mvn profile sample-test for testng ios
        run: |
          cd ios/testng-examples
          mvn compile
          mvn test -P sample-test

      # 10. Chạy mvn profile sample-local-test cho iOS (sử dụng BrowserStack Local)
      - name: Run mvn profile sample-local-test for testng ios
        run: |
          cd ios/testng-examples
          mvn compile
          mvn test -P sample-local-test -D"browserstack.app"="./LocalSample.ipa"

      # 11. Đảm bảo rằng BrowserStack Local sẽ được đóng khi hoàn thành
      - name: Terminate BrowserStack Local
        run: |
          pkill BrowserStackLocal

      # 12. Cập nhật trạng thái kiểm tra khi công việc hoàn thành
      - if: always()
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        id: status-check-completed
        env:
          conclusion: ${{ job.status }}
          job_name: TestNG Appium Repo ${{ matrix.java }} - ${{ matrix.os }} Sample
          commit_sha: ${{ github.event.inputs.commit_sha }}
        with:
          github-token: ${{ github.token }}
          script: |
            const result = await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: process.env.job_name,
            head_sha: process.env.commit_sha,
            status: 'completed',
            conclusion: process.env.conclusion
            }).catch((err) => ({status: err.status, response: err.response}));
            console.log(`The status-check response : ${result.status} Response : ${JSON.stringify(result.response)}`)
            if (result.status !== 201) {
              console.log('Failed to create check run')
            }
